name: bia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2

  # Env
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.7.0

  # State Management
  provider: ^6.1.2

  # Formatting
  intl: ^0.19.0

  # Hardware
  mobile_scanner: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
